#!/bin/bash

#Description:Intallation of jenkins

#Author:Joshua

#Date:Febuary 2022

echo "you are about to have a jenkins installation experince : "

sleep 4

yum install java-1.8.0-openjdk-devel

sleep 3

wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo 
  
sleep 3
    
sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/jenkins.repo
      
sleep 3
        
yum install jenkins
	  
sleep3
	    
systemctl start jenkins
	      
sleep 3
	        
systemctl status jenkins

sleep 3

firewall-cmd --permanent --zone=public --add-port=8080/tcp 

sleep 3

firewall-cmd --reload





		  
		   
